### ISSUE TITLE
Figure out how to call and catch JSON objects in swift 

### ISSUE THREAD

**Issue by pgicking** [Routelandia/routelandia-iOS#5]
I was going to do a basic hit against highways and figure out how to catch the response in swift.

**Comment by joshproehl** [comment]
We should make sure that we do this in a generic "api fetcher"  type class which creates entity objects from the returned JSON, and uses the entity classes to create the JSON structures to send.

**Comment by pgicking** [comment]
Figured out how to do it synchronously, async was too much of a hassle. Working on apifetcher, closing this issue for now
